## Tetrax AI assesment

### First we are importing the datasets

In [2]:
import pandas as pd

publicationProjectLinkUrl = "publicationprojectlink.csv"
sample_projects_url = "sample_projects.csv"
sample_publications_url = "sample_publications.csv"


publicationProjectLinkdf = pd.read_csv(publicationProjectLinkUrl)
sample_projects_df = pd.read_csv(sample_projects_url)
sample_publications_df =pd.read_csv(sample_publications_url)

### Previsualization of the datasets

In [3]:
publicationProjectLinkdf

,publication_uuid,project_uuid,created_at
0,a1becda7-878a-4531-baef-ac19a99f219d,fa01caab-85a9-4750-bb8c-582fae234cce,2025-06-23 08:55:27.165958
1,f659d3c7-3963-4349-984f-f725dd053bc4,7f1fe1a7-39c3-4e65-b53e-09b89b230746,2025-06-23 08:55:27.166048
2,067e134e-b0ce-4aed-af0b-f0c7cd0c1fd3,14ad070e-e1f3-4abf-8f91-47cf84e2d840,2025-06-23 08:55:27.166119
3,be0beb53-3386-4dce-87e2-a8d8f71fe07b,7067a5c3-9d02-40fb-8159-93d2a13a1c59,2025-06-23 08:55:27.166185
4,3c231172-001f-4007-a87b-0a7407c3f928,47346cfd-b4c8-4bde-a3b7-1007eaf64ec3,2025-06-23 08:55:27.166250
...,...,...,...
21714,d1ddcdcb-1a23-4e8c-9723-372cd30b9bac,37b28581-faf7-4111-a13f-9faf6f20324c,2025-06-23 08:55:33.793149
21715,00c26704-a2f7-400f-a638-d2a8a84501f8,2b214d14-75fb-4ef2-9fd6-bc71a8cbe2f2,2025-06-23 08:55:33.793211
21716,e6b28f85-c87b-44a0-aff2-d6867eee4b61,062b9ee0-db98-498c-b036-de48e6ff2a20,2025-06-23 08:55:33.793288
21717,52fcb97b-3bc5-4c4f-be4a-604f03277c60,d05026a7-bd47-4542-ad69-abe24b17c8e8,2025-06-23 08:55:33.793351
21718,52fcb97b-3bc5-4c4f-be4a-604f03277c60,9a4cd691-b4c6-45ee-86e9-3d5229e3c530,2025-06-23 08:55:33.793367

In [4]:
publicationProjectLinkdf.describe()

,publication_uuid,project_uuid,created_at
count,21719,21719,21719
unique,16463,10388,21719
top,fd6b60ef-48b6-4ece-9181-5168337cfa7e,a16be21c-8eab-49a5-a3d1-998945d62770,2025-06-23 08:55:27.165958
freq,17,52,1

In [5]:
sample_projects_df

,uuid,name,type,capacity_value,capacity_units,access_node_uuid,created_at,updated_at
0,e8c34def-8903-4c23-98f4-0b68fe3015ce,Instalación fotovoltaica en tejado del colegio...,generation,0.00100,MW,NaN,2025-06-19 15:36:36.404333,2025-06-19 15:36:36.404341
1,ff2c4daf-40d5-4c04-a968-4a559e2a4d0e,Instalación fotovoltaica de producción de ener...,generation,1.00000,MW,NaN,2025-06-19 15:34:30.745488,2025-06-19 15:34:30.745495
2,c3035163-49ef-4574-bd8b-21daeef7ce77,Parque Eólico Las Casillas,generation,3.15000,MWn,NaN,2025-06-19 15:42:09.208022,2025-06-19 15:42:09.208031
3,284cc20b-5e3a-42ae-a7a3-6734531bb6de,Modificado Parque Eólico Villaumbrales,generation,48.00000,MW,NaN,2025-06-19 15:34:38.784710,2025-06-19 15:34:38.784716
4,61b40106-e604-490a-a6c9-5c0625048c12,Línea de acometida de 400 kV desde la subestac...,grid,400.00000,KV,NaN,2025-06-19 15:29:49.913154,2025-06-19 15:29:49.913160
...,...,...,...,...,...,...,...,...
1033,e77de075-1b7c-4361-9283-6def0fdf6bcc,Línea subterránea de transporte SE Virgen de Á...,grid,132.00000,KV,NaN,2025-06-19 15:31:06.911585,2025-06-19 15:31:06.911592
1034,1df51a28-8db5-42a2-9166-988aaf8de2b9,Parque Fotovoltaico Alpera I,generation,0.98974,MW,NaN,2025-06-19 15:45:13.545445,2025-06-19 15:45:13.545451
1035,47715462-4a8a-465b-84db-80b4edd4f0e5,Soterramiento tramo de la línea aérea de media...,grid,20.00000,KV,NaN,2025-06-19 15:38:58.428692,2025-06-19 15:38:58.428699
1036,2af88989-fffd-458a-a783-1c0d4fcefd4c,Parque eólico Pena Galluda,generation,3.45000,MW,NaN,2025-06-19 15:24:08.280895,2025-06-19 15:24:08.280902
1037,cb39505b-56d6-4f9c-84a9-2576e1bfbe5f,"Nueva línea aérea media tensión conductor 94, ...",grid,20.00000,KV,NaN,2025-06-19 15:28:45.181082,2025-06-19 15:28:45.181087

In [6]:
unique_values = sample_projects_df['capacity_units'].unique()
print(unique_values)

['MW' 'MWn' 'KV' nan 'MWp' 'm3/h' 'km' 'MWh']

#### After visualizing the data in Retool, I realized there were some unit errors in the dataset. Therefore, we are modifying the units according to the type of project (generation, storage, or grid).

In [7]:
##

sample_projects_df

unique_values = sample_projects_df['capacity_units'].unique()

type_to_unit = {
    'generation': 'MW',
    'storage': 'MWh',
    'grid': 'KV'
}

# Ensure type is lowercase to match mapping
sample_projects_df['type_lower'] = sample_projects_df['type'].str.lower()

# Create a new Series of updated units from the mapping
new_units = sample_projects_df['type_lower'].map(type_to_unit)

# Only update where a match was found in the mapping
sample_projects_df['capacity_units'] = new_units.combine_first(sample_projects_df['capacity_units'])

# Optional: drop the helper column
sample_projects_df.drop(columns='type_lower', inplace=True)

sample_projects_df

,uuid,name,type,capacity_value,capacity_units,access_node_uuid,created_at,updated_at
0,e8c34def-8903-4c23-98f4-0b68fe3015ce,Instalación fotovoltaica en tejado del colegio...,generation,0.00100,MW,NaN,2025-06-19 15:36:36.404333,2025-06-19 15:36:36.404341
1,ff2c4daf-40d5-4c04-a968-4a559e2a4d0e,Instalación fotovoltaica de producción de ener...,generation,1.00000,MW,NaN,2025-06-19 15:34:30.745488,2025-06-19 15:34:30.745495
2,c3035163-49ef-4574-bd8b-21daeef7ce77,Parque Eólico Las Casillas,generation,3.15000,MW,NaN,2025-06-19 15:42:09.208022,2025-06-19 15:42:09.208031
3,284cc20b-5e3a-42ae-a7a3-6734531bb6de,Modificado Parque Eólico Villaumbrales,generation,48.00000,MW,NaN,2025-06-19 15:34:38.784710,2025-06-19 15:34:38.784716
4,61b40106-e604-490a-a6c9-5c0625048c12,Línea de acometida de 400 kV desde la subestac...,grid,400.00000,KV,NaN,2025-06-19 15:29:49.913154,2025-06-19 15:29:49.913160
...,...,...,...,...,...,...,...,...
1033,e77de075-1b7c-4361-9283-6def0fdf6bcc,Línea subterránea de transporte SE Virgen de Á...,grid,132.00000,KV,NaN,2025-06-19 15:31:06.911585,2025-06-19 15:31:06.911592
1034,1df51a28-8db5-42a2-9166-988aaf8de2b9,Parque Fotovoltaico Alpera I,generation,0.98974,MW,NaN,2025-06-19 15:45:13.545445,2025-06-19 15:45:13.545451
1035,47715462-4a8a-465b-84db-80b4edd4f0e5,Soterramiento tramo de la línea aérea de media...,grid,20.00000,KV,NaN,2025-06-19 15:38:58.428692,2025-06-19 15:38:58.428699
1036,2af88989-fffd-458a-a783-1c0d4fcefd4c,Parque eólico Pena Galluda,generation,3.45000,MW,NaN,2025-06-19 15:24:08.280895,2025-06-19 15:24:08.280902
1037,cb39505b-56d6-4f9c-84a9-2576e1bfbe5f,"Nueva línea aérea media tensión conductor 94, ...",grid,20.00000,KV,NaN,2025-06-19 15:28:45.181082,2025-06-19 15:28:45.181087

####Saving the updated dataset

In [8]:
output_path = "updated_sample_projects.csv"  # You can change this path and filename

sample_projects_df.to_csv(output_path, index=False)  # Save without row indices

In [9]:
sample_projects_df.describe(include='all')

,uuid,name,type,capacity_value,capacity_units,access_node_uuid,created_at,updated_at
count,1038,1038,1038,946.000000,1029,361,1038,1038
unique,1038,1038,5,NaN,5,226,1038,1038
top,e8c34def-8903-4c23-98f4-0b68fe3015ce,Instalación fotovoltaica en tejado del colegio...,generation,NaN,MW,3888b821-bcab-4133-ac80-70f9ff0fc74d,2025-06-19 15:36:36.404333,2025-06-19 15:36:36.404341
freq,1,1,763,NaN,767,7,1,1
mean,NaN,NaN,NaN,72.143869,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,307.734297,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,0.001000,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,4.256700,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,25.000000,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,50.000000,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,6998.110000,NaN,NaN,NaN,NaN

In [10]:
# Check for null values in capacity_value or capacity_units
null_capacity_value = sample_projects_df[sample_projects_df['capacity_value'].isnull()]
null_capacity_units = sample_projects_df[sample_projects_df['capacity_units'].isnull()]

print("Projects with NULL capacity_value:")
print(null_capacity_value[['uuid', 'name', 'type', 'capacity_value', 'capacity_units']])

print("\nProjects with NULL capacity_units:")
print(null_capacity_units[['uuid', 'name', 'type', 'capacity_value', 'capacity_units']])

# Summary count of nulls by project type
print("\nCount of null capacity_value by project type:")
print(null_capacity_value['type'].value_counts())

print("\nCount of null capacity_units by project type:")
print(null_capacity_units['type'].value_counts())

Projects with NULL capacity_value:
                                      uuid  \
5     94202a83-ddc9-4925-a069-d2e472560b00
26    099d94fc-4959-4ef6-9341-7d1ac5f9e91e
31    a5aef067-46bd-4ba1-9992-c6c0c95831d9
32    670f30f4-e131-4f06-80c6-e3c52ce64aeb
66    d8c847e1-1103-44d6-bf5c-e17e95b841ee
...                                    ...
969   6d12c787-407e-4948-85df-b8ea11040225
976   fa9bb311-e3c0-4033-b6ee-4bcd0e26e620
1003  38fbfb3f-f35d-4aea-b06a-71d9a8123aae
1007  be9cbdd3-124b-4636-ac47-7896f5695345
1009  4db61af4-5ec4-4f06-b304-c2fe427a8c35

                                                   name        type  \
5     Almacenamiento temporal de residuos peligrosos...       other
26    Almacén de productos de repostería y materias ...      demand
31                           La Muela II Repotenciación  generation
32                                Parque eólico Hépotas  generation
66                                    CSF El Campello I  generation
...                                                 ...         ...
969                                         Choca Solar  generation
976                                        PSFV Carreró  generation
1003  Proyecto de soterramiento de la línea aérea de...        grid
1007                                       FV Ronda III  generation
1009            Geriátrico en Calle el Estudio, Solares      demand

      capacity_value capacity_units
5                NaN            NaN
26               NaN            NaN
31               NaN             MW
32               NaN             MW
66               NaN             MW
...              ...            ...
969              NaN             MW
976              NaN             MW
1003             NaN             KV
1007             NaN             MW
1009             NaN            NaN

[92 rows x 5 columns]

Projects with NULL capacity_units:
                                      uuid  \
5     94202a83-ddc9-4925-a069-d2e472560b00
26    099d94fc-4959-4ef6-9341-7d1ac5f9e91e
174   f0a82bb8-9e94-4116-b652-7c64936ba445
356   938c10d8-0e04-4b06-8365-74126679c563
391   76c9a44a-c7e7-495e-ab54-1a35ecb7ac19
447   69a7e2cf-3d0c-4166-85da-ace141a652a8
587   82fc199a-11ec-4692-b7a7-f5a45127cd24
772   b7f78d40-8d0d-4efa-956b-73b31d66bb48
1009  4db61af4-5ec4-4f06-b304-c2fe427a8c35

                                                   name    type  \
5     Almacenamiento temporal de residuos peligrosos...   other
26    Almacén de productos de repostería y materias ...  demand
174        Aprovechamiento de agua de la regata Karrika  demand
356   Proyecto de mejora en el aprovechamiento de ag...   other
391   Proyecto de Distribución de agua con bombeos f...  demand
447   Ampliación de almacenamiento de equipos y maqu...   other
587   Proyecto de Actuación Especial para actividad ...   other
772   Instalación de almacenamiento y red de distrib...   other
1009            Geriátrico en Calle el Estudio, Solares  demand

      capacity_value capacity_units
5                NaN            NaN
26               NaN            NaN
174              NaN            NaN
356              NaN            NaN
391              NaN            NaN
447              NaN            NaN
587              NaN            NaN
772              NaN            NaN
1009             NaN            NaN

Count of null capacity_value by project type:
generation    71
grid          12
other          5
demand         4
Name: type, dtype: int64

Count of null capacity_units by project type:
other     5
demand    4
Name: type, dtype: int64

#### We can see there are some missing values in different project categories. These missing data points might affect our results, so we should decide how to handle them carefully.

In [11]:
sample_publications_df

,uuid,date,url,is_correction,status,source,milestones,created_at,updated_at
0,7731fdba-bcf7-49a9-9d79-72b09de6e2c8,2021-09-30 00:00:00,https://docm.jccm.es/docm/./descargarArchivo.d...,True,conditionally_approved,docm,"AAC,AAP,DIA,IP",2025-06-19 14:19:42.420955,2025-06-19 14:19:42.420962
1,2299f64d-6f5f-4bc2-90cd-9642f6d6c4b9,2024-12-31 00:00:00,https://bocyl.jcyl.es/boletines/2024/12/31/pdf...,False,approved,bocyl,"DUP,IP",2025-06-19 14:18:35.816392,2025-06-19 14:18:35.816398
2,db082244-8251-4a6a-9d77-700b645d9a09,2021-08-05 00:00:00,https://www.caib.es//eboibfront/pdf/es/2021/10...,False,approved,boib,DUP,2025-06-19 14:18:26.150337,2025-06-19 14:18:26.150343
3,93d8d508-9516-4939-9396-f11d7f204e61,2020-11-14 00:00:00,https://www.boe.es/boe/dias/2020/11/14/pdfs/BO...,False,approved,boe,"DUP,IP",2025-06-19 14:18:24.383521,2025-06-19 14:18:24.383528
4,4af39168-e9be-4962-82ac-a274b1ec2b0e,2021-12-02 00:00:00,https://docm.jccm.es/docm/./descargarArchivo.d...,False,approved,docm,"AAP,IP",2025-06-19 14:19:43.343259,2025-06-19 14:19:43.343267
...,...,...,...,...,...,...,...,...,...
1641,ed003ac1-8a4a-4330-bb46-b2c0a8703462,2021-09-24 00:00:00,https://bocyl.jcyl.es/boletines/2021/09/24/pdf...,False,approved,bocyl,"AAC,DUP,IP",2025-06-19 14:18:40.604918,2025-06-19 14:18:40.604924
1642,2c5761b4-512f-43da-8ec3-7439b1dd40e7,2021-05-20 00:00:00,https://www.boa.aragon.es/cgi-bin/EBOA/BRSCGI?...,False,approved,boa,"AAP,IP",2025-06-19 14:19:22.101071,2025-06-19 14:19:22.101077
1643,a128f387-b103-4f15-b1cc-d93456d7bbee,2021-10-05 00:00:00,https://docm.jccm.es/docm/./descargarArchivo.d...,False,approved,docm,AAP,2025-06-19 14:19:41.541082,2025-06-19 14:19:41.541088
1644,d0c20b48-1ca9-46b9-a6ad-690fd82bbb42,2023-11-30 00:00:00,https://www.boe.es/boe/dias/2023/11/30/pdfs/BO...,True,approved,boe,DUP,2025-06-19 14:18:09.955972,2025-06-19 14:18:09.955978
1645,e05d1702-bf38-470f-83e1-6d2c26c7137c,2022-05-12 00:00:00,https://docm.jccm.es/docm/./descargarArchivo.d...,True,approved,docm,"AAC,AAP",2025-06-19 14:19:28.343317,2025-06-19 14:19:28.343325

In [12]:
sample_publications_df.describe(include='all')

unique_values = df['id'].unique()
print(unique_ids)

NameError: name 'df' is not defined

In [13]:
sample_publications_df[["uuid", "url"]]

sample_publications_joined = sample_publications_df[["uuid", "url"]].merge(
    publicationProjectLinkdf,
    left_on="uuid",                # column from sample_publications_df
    right_on="publication_uuid",   # column from publicationProjectLinkdf
    how="left"                    # use "left", "right", or "outer" as needed
)


sample_publications_joined

,uuid,url,publication_uuid,project_uuid,created_at
0,7731fdba-bcf7-49a9-9d79-72b09de6e2c8,https://docm.jccm.es/docm/./descargarArchivo.d...,7731fdba-bcf7-49a9-9d79-72b09de6e2c8,f725346f-2a6c-4e9a-a1ba-db44f867fa5c,2025-06-23 08:55:33.744073
1,2299f64d-6f5f-4bc2-90cd-9642f6d6c4b9,https://bocyl.jcyl.es/boletines/2024/12/31/pdf...,2299f64d-6f5f-4bc2-90cd-9642f6d6c4b9,404ad663-db28-419e-99e1-5e9072111895,2025-06-23 08:55:30.092683
2,db082244-8251-4a6a-9d77-700b645d9a09,https://www.caib.es//eboibfront/pdf/es/2021/10...,db082244-8251-4a6a-9d77-700b645d9a09,7a6751db-978f-4f0e-8e2e-101d76542072,2025-06-23 08:55:29.578136
3,93d8d508-9516-4939-9396-f11d7f204e61,https://www.boe.es/boe/dias/2020/11/14/pdfs/BO...,93d8d508-9516-4939-9396-f11d7f204e61,f44bc83d-33fb-4e73-b991-a5b451acd753,2025-06-23 08:55:29.473230
4,4af39168-e9be-4962-82ac-a274b1ec2b0e,https://docm.jccm.es/docm/./descargarArchivo.d...,4af39168-e9be-4962-82ac-a274b1ec2b0e,0673c28f-470c-4891-99af-c61edb811496,2025-06-23 08:55:33.790969
...,...,...,...,...,...
2170,a128f387-b103-4f15-b1cc-d93456d7bbee,https://docm.jccm.es/docm/./descargarArchivo.d...,a128f387-b103-4f15-b1cc-d93456d7bbee,a7307db0-d4e1-40d4-80ee-4e0ab042f004,2025-06-23 08:55:33.699645
2171,a128f387-b103-4f15-b1cc-d93456d7bbee,https://docm.jccm.es/docm/./descargarArchivo.d...,a128f387-b103-4f15-b1cc-d93456d7bbee,1addb12a-63f2-4cf8-aa4a-eb45ab75f770,2025-06-23 08:55:33.699665
2172,a128f387-b103-4f15-b1cc-d93456d7bbee,https://docm.jccm.es/docm/./descargarArchivo.d...,a128f387-b103-4f15-b1cc-d93456d7bbee,545ff741-d09e-40df-84ee-286cce4e7c50,2025-06-23 08:55:33.699684
2173,d0c20b48-1ca9-46b9-a6ad-690fd82bbb42,https://www.boe.es/boe/dias/2023/11/30/pdfs/BO...,d0c20b48-1ca9-46b9-a6ad-690fd82bbb42,55e588a3-8043-4ba3-bfa3-6d688bb7d91d,2025-06-23 08:55:28.806281
2174,e05d1702-bf38-470f-83e1-6d2c26c7137c,https://docm.jccm.es/docm/./descargarArchivo.d...,e05d1702-bf38-470f-83e1-6d2c26c7137c,aede1a3e-fba4-4386-a514-2a15c661cf97,2025-06-23 08:55:32.855076

In [ ]:
import pandas as pd
from sqlalchemy import create_engine

# Replace with your actual Retool PostgreSQL URL
RETOOL_DB_URL = "postgresql://retool:npg_PCpNSADo8v3g@ep-dawn-resonance-a6hbyi72.us-west-2.retooldb.com/retool?sslmode=require"

# Load CSV files
df1 = sample_publications_df
df2 = sample_projects_df


# Connect to Retool database
engine = create_engine(RETOOL_DB_URL)

# Write DataFrames to Retool (PostgreSQL) as new tables
df1.to_sql('table1', engine, if_exists='replace', index=False)
df2.to_sql('table2', engine, if_exists='replace', index=False)

print("✅ Both CSV files uploaded to Retool!")

In [ ]:
pip install pandas sqlalchemy psycopg2

### Pipeline to connect SQL to database

In [16]:
import pandas as pd
from sqlalchemy import create_engine
import urllib.parse

# Retool connection details
RETOOL_DB_URL = (
    "postgresql+psycopg2://retool:npg_PCpNSADo8v3g"
    "@ep-dawn-resonance-a6hbyi72.us-west-2.retooldb.com:5432"
    "/retool?sslmode=require"
)

# Load CSV files
df1 = sample_publications_df
df2 = sample_projects_df

# Connect and upload to Retool
engine = create_engine(RETOOL_DB_URL)

df1.to_sql('sample_projects', engine, if_exists='replace', index=False)
df2.to_sql('updated_sample_publications', engine, if_exists='replace', index=False)

print("✅ Successfully uploaded CSVs to Retool PostgreSQL!")

✅ Successfully uploaded CSVs to Retool PostgreSQL!